---
project_name: athenz-user-cert
release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
# https://github.com/goreleaser/goreleaser/blob/v1.13.1/www/docs/customization/build.md
builds:
  - id: "athenz-user-cert"
    dir: .
    main: ./cmd
    binary: athenzusercert
    ignore:
      - goos: darwin
        goarch: 386
    # Custom ldflags.
    # For more info refer to: https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies
    # and https://pkg.go.dev/cmd/link
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'.
    # Templates: allowed.
    #ldflags:
    #  - -s -w -X main.build={{.Version}}
archives:
  - id: homebrew
    format: zip
# GoReleaser publishes formulae to <owner>/<repository>.
# This project currently uses the source repository itself as the tap repository via `brew tap <owner>/athenz-user-cert https://github.com/<owner>/athenz-user-cert`.
brews:
  - repository:
      owner: "{{ .Env.HOMEBREW_TAP_OWNER }}"
      name: "{{ .Env.HOMEBREW_TAP_REPOSITORY }}"
    name: athenz-user-cert
    directory: Formula
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    description: CLI to retrieve Athenz-compatible User Certificate
    ids:
      - homebrew
    test: |
      system "#{bin}/athenzusercert version"
