# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/ctyano/athenz-user-cert"
  version "0.0.313"

  on_macos do
    on_intel do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.313/athenz-user-cert_0.0.313_darwin_amd64.zip"
      sha256 "e97f61de79b0257cd3a317369d170ca7eab233dfc43cfe1d5136ea471f832be0"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.313/athenz-user-cert_0.0.313_darwin_arm64.zip"
      sha256 "be59f190cb1b8ff7ab53ca94989b1830658535c67606760c2e537163e3a44627"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.313/athenz-user-cert_0.0.313_linux_amd64.zip"
        sha256 "36532642d17d9cc8f519ed9b08ee3754e2a8d47fc94e8e11ee82d2e155666f15"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.313/athenz-user-cert_0.0.313_linux_arm64.zip"
        sha256 "5eeffbc97e311ffeec34036853d45b1e572d5741d61d3c9ac11162a629c77334"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
